steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 
    'gcr.io/$PROJECT_ID/${_CLOUD_RUN_SERVICE}', 
    '.'
    ]
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_CLOUD_RUN_SERVICE}']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['tag',
    'gcr.io/$PROJECT_ID/${_CLOUD_RUN_SERVICE}']
images:
- gcr.io/$PROJECT_ID/${_CLOUD_RUN_SERVICE}

options:
    substitution_option: 'ALLOW_LOOSE'
    logging: CLOUD_LOGGING_ONLY

substitutions:
    _APP_DEBUG: 'true'