 steps:
 # build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/[${_CLOUD_RUN_SERVICE}]:$COMMIT_SHA', '.']
 # push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/[${_CLOUD_RUN_SERVICE}]:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/cloud-builders/gcloud'
   args:
   - 'run'
   - 'deploy'
   - '[${_CLOUD_RUN_SERVICE}]'
   - '--image'
   - 'gcr.io/$PROJECT_ID/[${_CLOUD_RUN_SERVICE}]:$COMMIT_SHA'
   - '--region'
   - '[REGION]'
 images:
 - 'gcr.io/$PROJECT_ID/[${_CLOUD_RUN_SERVICE}]:$COMMIT_SHA'

 options:
    substitution_option: 'ALLOW_LOOSE'
    logging: CLOUD_LOGGING_ONLY